# Generated by Django 3.0.5 on 2020-06-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employeeId', models.IntegerField(unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=512)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
