# Generated by Django 3.0.5 on 2020-06-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hierarchy', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
