# Generated by Django 3.0.6 on 2020-08-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0002_activity_leaves_availed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='Customer_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='Day',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='Leaves_availed',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='Manager',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='Project_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='Vendor_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='Work_location',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='employeeName',
        ),
    ]
