# Generated by Django 3.0.6 on 2020-08-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0003_auto_20200807_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='Customer_name',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='choices',
            name='Manager',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='choices',
            name='Project_No',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='choices',
            name='Project_code',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='choices',
            name='Project_name',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='choices',
            name='Vendor_name',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='choices',
            name='employeeId',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
