# Generated by Django 3.0.6 on 2020-08-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0004_auto_20200810_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='choices',
        ),
    ]
