# Generated by Django 3.0.5 on 2020-08-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0005_remove_choices_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Total_hours',
            field=models.IntegerField(default=None),
        ),
    ]
