# Generated by Django 3.0.6 on 2020-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0005_remove_choices_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Total_hours',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='employeeId',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='choices',
            name='employeeId',
            field=models.IntegerField(default=None),
        ),
    ]
