# Generated by Django 3.0.5 on 2020-08-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0006_auto_20200811_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='employeeId',
            field=models.IntegerField(default=None),
        ),
    ]
