# Generated by Django 3.0.5 on 2020-05-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(choices=[('1', 'Placeholder'), ('2', 'While'), ('3', 'We'), ('4', 'Figure'), ('5', 'This'), ('6', 'Out')], max_length=200)),
                ('AddComments', models.TextField(max_length=1000)),
            ],
        ),
    ]
