# Generated by Django 3.0.5 on 2020-06-08 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='AddComments',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='Project',
            field=models.CharField(choices=[('1', 'Placeholder'), ('2', 'While'), ('3', 'We'), ('4', 'Figure'), ('5', 'This'), ('6', 'Out')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='employeeId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
