# Generated by Django 3.0.5 on 2020-06-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0002_auto_20200608_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='employeeId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
