# Generated by Django 3.0.5 on 2020-06-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0002_auto_20200608_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='logged_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
