# Generated by Django 3.0.5 on 2020-06-12 23:37

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0003_auto_20200612_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', django_mysql.models.ListCharField(models.CharField(max_length=256), max_length=1542, size=6)),
            ],
        ),
    ]
