# Generated by Django 3.0.5 on 2020-08-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0006_activity_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
    ]
