# Generated by Django 3.0.5 on 2020-06-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdef',
            name='previous_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='previous login'),
        ),
    ]
