# Generated by Django 3.0.5 on 2020-06-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0002_userdef_previous_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdef',
            name='previous_login',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userdef',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Director', 'Director'), ('Sr. Manager', 'Sr. Manager'), ('Manager', 'Manager'), ('Sr. Engineer', 'Sr. Engineer'), ('Assistant Regional Manager', 'Assistant Regional Manager'), ('Assistant to the Regional Manager', 'Assistant to the Regional Manager')], max_length=2048),
        ),
    ]
