# Generated by Django 3.0.5 on 2020-08-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0003_auto_20200628_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc', models.IntegerField(unique=True)),
            ],
        ),
    ]
