# Generated by Django 3.0.6 on 2020-08-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0004_logincount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdef',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('HR', 'Human Resources'), ('Employee', 'Employee')], max_length=2048),
        ),
    ]
